# Variables
DATASET_PATH = '../../data/Signature/dataset/'
MODEL_NAME = '20211206_1136'
MODEL_PATH = f'./models/{MODEL_NAME}/model.h5'
LOG_PATH = f'./logs/{MODEL_NAME}'
IMG_SIZE = 150
BATCH_SIZE = 32
SHUFFLE_BUFFER_SIZE = 100
IMG_SHAPE = (IMG_SIZE, IMG_SIZE, 3)
LEARNING_RATE = 0.0001
NO_OF_EPOCHS = 30